services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - local_storage:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
  local_storage:
    driver: local

networks:
    default:
      name: data-dashboard-network