name: End 2 End Tests with Playwright
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Build and start services
      run: docker compose -f docker-compose-dev.yml up -d --build
    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to be ready..."
        for i in {1..30}; do
          if curl -s http://localhost:3000/ > /dev/null; then
            echo "Services are ready!"
            break
          fi
          echo "Waiting for services to be ready..."
          sleep 5
        done
    - name: Install dependencies
      working-directory: frontend
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: frontend
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: frontend
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
