name: End 2 End Tests with Playwright
on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and start services
      run: |
        cd ..
        docker compose -f docker-compose-dev.yml up -d --build
    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to be ready..."
        for i in {1..30}; do
          if curl -s http://localhost:3000/ > /dev/null; then
            echo "Services are ready!"
            break
          fi
          echo "Waiting for services to be ready..."
          sleep 5
        done
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: |
        rm -rf frontend/node_modules
        npm cache clean --force
        npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
